### ISSUE TITLE
Cannot read NIST UV/Vis spectra

### ISSUE THREAD

**Issue by alex-l-m** [bryanhanson/readJDX#11]
NIST has UV/Vis spectra for many molecules, for example: [o-Chloroaniline](https://webbook.nist.gov/cgi/cbook.cgi?ID=C95512&Units=SI)

The spectrum for that molecule is attached.

[C95512.txt](https://github.com/bryanhanson/readJDX/files/6971846/C95512.txt)

When I try to read it, I get the following error:

> Error in findVariableLists(jdx, debug) : Couldn't find any variable lists. Supported formats are: XYY, XRR, XII, NMR_2D, LC_MS, PEAK_TABLE

**Comment by bryanhanson** [comment]
Alex, I can add this w/i a few days.  It’s essentially the same as another format.  Bryan

**Comment by bryanhanson** [comment]
You can now read this type of file by using the `devel` branch (via https://github.com/bryanhanson/readJDX/commit/f002635892cf8958befac0a576da9049adddb5be).  I've got a few more improvements unrelated to this issue before I update the CRAN version (I also just submitted a new version to CRAN, and have to wait about 30 days to send another one).
