### ISSUE TITLE
set output directory for splitMultiblockDX

### ISSUE THREAD

**Issue by pstahlhofen** [bryanhanson/readJDX#16]
It would be a useful feature to set an output directory for `spllitMultiblockDX`. That way, the function would not need to fill the current working directory with files.

**Comment by bryanhanson** [comment]
Are you thinking passing a random path as an argument, or creating a subdir w/i the dir that contains the file being split into pieces?

**Comment by pstahlhofen** [comment]
I thought maybe one could pass the name of a subdir and then the method would create this inside the current directory and store the new files in it.

**Comment by bryanhanson** [comment]
Fixed in the `devel` branch.  Please test and report back.  Thanks.
