### ISSUE TITLE
Couldn't find any variable lists.  Supported formats are: XYY, XRR, XII, NMR_2D

### ISSUE THREAD

**Issue by Philip-Braun** [bryanhanson/readJDX#7]
Hi,

Thanks for the package! I Want to read a .jdx file (attached) like:
```
[install.packages("readJDX")
library(readJDX)
spectra <- readJDX("2.jdx")
```
I get the following error message:

Couldn't find any variable lists.  Supported formats are: XYY, XRR, XII, NMR_2D

What am I doing wrong?

[sample.txt](https://github.com/bryanhanson/readJDX/files/3955827/sample.txt)

**Comment by bryanhanson** [comment]
You are not doing anything wrong!  That file format is not supported.  It's a simple list of x, y values preceded by the metadata.  You can read that data in using some variation of `read.table` setting `skip` to the number of lines of metadata to skip and then figuring out the separator.  For that particular file, this worked:
```
pb <- read.table("sample.txt", sep = " ", skip = 31)
```
If you have a series of files, you can put this into a loop and set up a matrix to hold the results.  Let me know if you have further questions!

**Comment by Philip-Braun** [comment]
Wow,

I did not think one could just read it so easily.

Thank you very much!

**Comment by bryanhanson** [comment]
Depending upon the final destination for this data, there are several other ways one might capture it, so just let me know if you need assistance.
