### ISSUE TITLE
readJDX

### ISSUE THREAD

**Issue by Vineethreddy25** [bryanhanson/readJDX#8]
@bryanhanson 
Hello Mr Bryan, 
I am trying to open .jdx files into R by using readJDX and this error is showing up **Compound (multi-block / multi-spectra) data sets not supported**. It is for my Research Project. Hope you can help with this issue.

Warm Regards
Vinith Reddy Chandupatla

**Comment by bryanhanson** [comment]
Hello Vinith... the error is correct, files with multiple spectra in them are not currently supported.  The exception is 2D NMR files, but those should not give the error.  Can you e-mail me a sample file so I can take a look at it?  It's possible there is a work-around.

**Comment by Vineethreddy25** [comment]
Hi Bryan, I sent you the files. please have a look and let me know if there is a possibility.

Thanks and Regards
Vinith Chandupatla.

**Comment by bryanhanson** [comment]
Thanks for sending the files.  I looked at `pits0.jdx` and it appears to contain 101 spectra named "pits".  Not sure if these are exact duplicates or replicates or samples.  File `Whole Olive 0.jdx` contains 13 spectra named "Olive#1", "Olive#2" etc.  I guess these are replicates of the same sample or different samples.  Not sure how these files were constructed -- perhaps you should look at your instrument's file export details.  Maybe it was a bulk export process?

If you cannot re-export with one spectrum per file and unique file names, you could use a text editor to disassemble these files into individual files.  If you open them the structure is pretty clear.

**Comment by bryanhanson** [comment]
OP split the files with a Python script.  Closing.
