### ISSUE TITLE
Compound (multi-block / multi-spectra) data sets not supported...still?

### ISSUE THREAD

**Issue by ebcraine** [bryanhanson/readJDX#9]
I know this issue has been posted, and it appears this issue still exists. Appreciate any support you can provide. I was excited about the potential to open .dx file in R.

**Comment by bryanhanson** [comment]
Hello @ebcraine the feature has not been added as you know.  The easiest work around is to separate the individual pieces of the file using a text editor and give them separate file names.  If you can share the file I would be glad to write a little function to do this for you.  In fact, I may add such a function to the package if it works well.  I have very limited internet right now (just moved) but I will check daily.

**Comment by ebcraine** [comment]
Thank you SO much for the quick response. I really appreciate it.

I have one.dx I have been messing around with on my home computer that is around 90MB. I will try to get to our NIR analyzer and export a file with only a few samples. Hopefully, that will be a good option to send via email or to upload.

Best of luck with your move and thank you again for your help.

-evan
___________________
Evan Craine
(He/His)

Graduate Research Assistant
Ph.D. Candidate - Crop Science
Sustainable Seed Systems Laboratory<https://www.sustainableseedsystems.org/>

I do not expect a response to my email outside of your regular work hours.
________________________________

**Comment by bryanhanson** [comment]
Very good.  E-mail to hanson@depauw.edu I am able to check internet in the late afternoons Arizona time.

**Comment by ebcraine** [comment]
I went ahead and sent an example to that email.

cheers - evan

___________________
Evan Craine
(He/His)

Graduate Research Assistant
Ph.D. Candidate - Crop Science
Sustainable Seed Systems Laboratory<https://www.sustainableseedsystems.org/>

I do not expect a response to my email outside of your regular work hours.
________________________________

**Comment by bryanhanson** [comment]
Surprise!  https://github.com/bryanhanson/readJDX/commit/83e0385e56dbd98acb21f55ec019cb6b83020b30 now has a function `splitMultiblockDX()` that will split multiblock files into separate files.  After that, one can use the usual `readJDX` functions to process the individual files. Will be on CRAN shortly.  @ebcraine this is the same as I sent you previously, it's just now official.
